footer_columns:
  - name: Get Involved
    links:
      - content: pages/code-of-conduct.md
      - title: Forum
        url: https://github.com/orgs/valkey-io/discussions
      - title: GitHub
        url: https://github.com/valkey-io
  - name: Resources
    links:
      - page: about.md
      - page: code-of-conduct.md
      - page: trademark-policy.md
  - name: Contact
    links:
      - page: connect.md
